// Code generated by topogen — DO NOT EDIT.
//
// Spec summary: 4 nodes, 5 edges.
//
// Nodes:
//   src    Input
//   gate   ReadGate
//   inhib  ChainInhibitor
//   right  InhibitRightGate
//
// Edges:
//   srcToGate          src.ToOut -> gate.FromValue
//   gateToInhib        gate.ToGated -> inhib.FromPrev
//   inhibToGate        inhib.ToNext -> gate.FromAck
//   inhibToRightLeft   inhib.ToEdge -> right.FromLeft
//   inhibToRightRight  inhib.ToEdge -> right.FromRight

package Wiring

import (
	CI "github.com/dtauraso/wirefold/nodes/ChainInhibitorNode"
	IRG "github.com/dtauraso/wirefold/nodes/InhibitRightGateNode"
	INN "github.com/dtauraso/wirefold/nodes/InputNode"
	RGN "github.com/dtauraso/wirefold/nodes/ReadGateNode"
	S "github.com/dtauraso/wirefold/nodes/SafeWorker"
)

func Wire() []S.Node {
	// Channels
	srcToGate := make(chan int, 1)
	gateToInhib := make(chan int, 1)
	inhibToGate := make(chan int, 1)
	inhibToRightLeft := make(chan int, 1)
	inhibToRightRight := make(chan int, 1)

	// Input externals
	srcInput := make(chan int, 2)
	srcInput <- 1
	srcInput <- 2

	// Dead-end outputs
	inhibToAck := make(chan int, 1)
	rightToPassed := make(chan int, 1)

	// Nodes
	src := INN.InputNode{Id: 0, Name: "src", Input: srcInput, ToNext: srcToGate}
	gate := RGN.ReadGateNode{Id: 0, Name: "gate", FromAck: inhibToGate, FromValue: srcToGate, ToGated: gateToInhib}
	inhib := CI.ChainInhibitorNode{Id: 0, Name: "inhib", FromPrev: gateToInhib, ToAck: inhibToAck, ToEdge: []chan<- int{inhibToRightLeft, inhibToRightRight}, ToNext: inhibToGate}
	right := IRG.InhibitRightGateNode{Id: 0, Name: "right", FromLeft: inhibToRightLeft, FromRight: inhibToRightRight, ToPassed: rightToPassed}

	return []S.Node{&src, &gate, &inhib, &right}
}
