// Code generated by topogen — DO NOT EDIT.
//
// Spec summary: 4 nodes, 5 edges.
//
// Nodes:
//   src    Input
//   gate   ReadGate
//   inhib  ChainInhibitor
//   right  InhibitRightGate
//
// Edges:
//   srcToGate          src.out -> gate.value
//   gateToInhib        gate.gated -> inhib.in
//   inhibAckToGate     inhib.out -> gate.ack
//   inhibToRightLeft   inhib.inhibitOut -> right.left
//   inhibToRightRight  inhib.inhibitOut -> right.right

package Wiring

import (
	CI "github.com/dtauraso/wirefold/nodes/ChainInhibitorNode"
	IRG "github.com/dtauraso/wirefold/nodes/InhibitRightGateNode"
	INN "github.com/dtauraso/wirefold/nodes/InputNode"
	RGN "github.com/dtauraso/wirefold/nodes/ReadGateNode"
	S "github.com/dtauraso/wirefold/nodes/SafeWorker"
)

func Wire() []S.Node {
	// Channels
	srcToGate := make(chan int, 1)
	gateToInhib := make(chan int, 1)
	inhibAckToGate := make(chan int, 1)
	inhibToRightLeft := make(chan int, 1)
	inhibToRightRight := make(chan int, 1)

	// Input externals
	srcInput := make(chan int, 2)
	srcInput <- 1
	srcInput <- 2

	// Dead-end outputs
	inhibAck := make(chan int, 1)
	rightPassed := make(chan int, 1)

	// Nodes
	src := INN.InputNode{Id: 0, Name: "src", Input: srcInput, ToNext: srcToGate}
	gate := RGN.ReadGateNode{Id: 0, Name: "gate", AckCh: inhibAckToGate, ValueCh: srcToGate, Gated: gateToInhib}
	inhib := CI.ChainInhibitorNode{Id: 0, Name: "inhib", FromPrev: gateToInhib, ToAck: inhibAck, ToEdge: []chan<- int{inhibToRightLeft, inhibToRightRight}, ToNext: inhibAckToGate}
	right := IRG.InhibitRightGateNode{Id: 0, Name: "right", FromLeft: inhibToRightLeft, FromRight: inhibToRightRight, ToPassed: rightPassed}

	return []S.Node{&src, &gate, &inhib, &right}
}
