// GENERATED by scripts/gen-node-defs.mjs — do not edit. Source: nodes/<Kind>/SPEC.md

export type DisplayKind = "queue" | "repeat" | "held";

export interface NodePort {
  id: string;
  accent?: string;
}

export interface NodeDef {
  defaultLabel: string;
  bg: string;
  border: string;
  text: string;
  accent: string;
  minWidth?: number;
  sublabel?: string;
  targets?: NodePort[];
  sources?: NodePort[];
  displays?: DisplayKind[];
}

export const NODE_DEFS: Record<string, NodeDef> = {
  andGate: { defaultLabel: "andGate", bg: "#e3f2fd", border: "#1565c0", text: "#0d47a1", accent: "#1565c0", minWidth: 70, targets: [{ id: "FromA" }, { id: "FromB" }], sources: [{ id: "ToOut", accent: "#42a5f5" }] },
  chainInhibitor: { defaultLabel: "chainInhibitor", bg: "#fff3e0", border: "#e65100", text: "#bf360c", accent: "#e65100", minWidth: 90, targets: [{ id: "FromPrev" }], sources: [{ id: "ToNext" }, { id: "ToAck" }, { id: "ToEdge" }, { id: "ToEdgeNew" }], displays: ["held"] },
  edgeNode: { defaultLabel: "edge", bg: "#fff8e1", border: "#ff6f00", text: "#e65100", accent: "#ff6f00", minWidth: 90, targets: [{ id: "FromLeft" }, { id: "FromRight" }], sources: [{ id: "ToInhibitor" }, { id: "ToPartition" }, { id: "ToNextEdge" }] },
  inhibitRightGate: { defaultLabel: "inhibitRightGate", bg: "#fce4ec", border: "#880e4f", text: "#880e4f", accent: "#880e4f", minWidth: 110, sublabel: "L pass / R inhibit", targets: [{ id: "FromLeft" }, { id: "FromRight", accent: "#f48fb1" }], sources: [{ id: "ToPassed" }] },
  input: { defaultLabel: "input", bg: "#1a1f2e", border: "#3fb950", text: "#c9d1d9", accent: "#3fb950", minWidth: 90, sources: [{ id: "ToOut" }], displays: ["queue", "repeat"] },
  partition: { defaultLabel: "partition", bg: "#fce4ec", border: "#ad1457", text: "#880e4f", accent: "#ad1457", minWidth: 90, targets: [{ id: "FromIn" }], sources: [{ id: "ToOut" }] },
  readGate: { defaultLabel: "readgate", bg: "#f3e5f5", border: "#7b1fa2", text: "#4a148c", accent: "#7b1fa2", minWidth: 70, sublabel: "val / ack", targets: [{ id: "FromValue" }, { id: "FromAck" }], sources: [{ id: "ToGated" }] },
  readLatch: { defaultLabel: "readlatch", bg: "#e0f7fa", border: "#00838f", text: "#006064", accent: "#00838f", minWidth: 90, sublabel: "FromIn / FromRelease", targets: [{ id: "FromIn" }, { id: "FromRelease", accent: "#80cbc4" }], sources: [{ id: "ToNext" }, { id: "ToAck" }] },
  streakBreakDetector: { defaultLabel: "streakBreakDetector", bg: "#ffebee", border: "#c62828", text: "#b71c1c", accent: "#c62828", minWidth: 110, targets: [{ id: "FromOld" }, { id: "FromNew" }], sources: [{ id: "ToDone" }] },
  streakDetector: { defaultLabel: "streakDetector", bg: "#e8f5e9", border: "#2e7d32", text: "#1b5e20", accent: "#2e7d32", minWidth: 100, targets: [{ id: "FromOld" }, { id: "FromNew" }], sources: [{ id: "ToDone" }, { id: "ToStreak", accent: "#66bb6a" }] },
  syncGate: { defaultLabel: "syncGate", bg: "#f3e5f5", border: "#7b1fa2", text: "#4a148c", accent: "#7b1fa2", minWidth: 70, targets: [{ id: "FromA" }, { id: "FromB" }], sources: [{ id: "ToRelease", accent: "#80cbc4" }] },
};
