// Code generated by tools/gen-kind-imports. DO NOT EDIT.

package main

import (
	_ "github.com/dtauraso/wirefold/nodes/ChainInhibitorNode"
	_ "github.com/dtauraso/wirefold/nodes/InhibitRightGateNode"
	_ "github.com/dtauraso/wirefold/nodes/InputNode"
	_ "github.com/dtauraso/wirefold/nodes/ReadGateNode"
)
