// Code generated by topogen — DO NOT EDIT.

package Wiring

import (
	CI "github.com/dtauraso/congenial-octo-pancake/ChainInhibitorNode"
	IRG "github.com/dtauraso/congenial-octo-pancake/InhibitRightGateNode"
	INN "github.com/dtauraso/congenial-octo-pancake/InputNode"
	RGN "github.com/dtauraso/congenial-octo-pancake/ReadGateNode"
	S "github.com/dtauraso/congenial-octo-pancake/SafeWorker"
)

func Wire() []S.Node {
	// Channels
	readGateToI0 := make(chan int, 1)
	i0ToI1 := make(chan int, 1)
	i1AckToReadGate := make(chan int, 1)
	inputToReadGate := make(chan int, 1)
	i0ToInhibitRight := make(chan int, 1)
	i1ToInhibitRight := make(chan int, 1)

	// Edge priming
	i1AckToReadGate <- 1

	// Input externals
	in0Input := make(chan int, 3)
	in0Input <- 0
	in0Input <- 1
	in0Input <- 0

	// Dead-end outputs
	i0TestAck := make(chan int, 1)
	i1Ack := make(chan int, 1)
	inhibitRight0Out := make(chan int, 1)

	// Nodes
	in0 := INN.InputNode{Id: 0, Name: "in0", Input: in0Input, ToNext: inputToReadGate}
	readGate1 := RGN.ReadGateNode{Id: 0, Name: "readGate1", FromAck: i1AckToReadGate, FromValue: inputToReadGate, ToLatch: readGateToI0}
	i0Test := CI.ChainInhibitorNode{Id: 0, Name: "i0Test", FromPrev: readGateToI0, ToAck: i0TestAck, ToEdge: []chan<- int{i0ToInhibitRight}, ToNext: i0ToI1}
	i1 := CI.ChainInhibitorNode{Id: 1, Name: "i1", FromPrev: i0ToI1, ToAck: i1Ack, ToEdge: []chan<- int{i1ToInhibitRight}, ToNext: i1AckToReadGate}
	inhibitRight0 := IRG.InhibitRightGateNode{Id: 0, Name: "inhibitRight0", FromLeft: i0ToInhibitRight, FromRight: i1ToInhibitRight, ToOut: inhibitRight0Out}

	return []S.Node{&in0, &readGate1, &i0Test, &i1, &inhibitRight0}
}
