// Code generated by topogen — DO NOT EDIT.
//
// Spec summary: 5 nodes, 6 edges.
//
// Nodes:
//   in0test        Input
//   readGate14     ReadGate
//   i0Test3        ChainInhibitor
//   myInhibitor    ChainInhibitor
//   inhibitRight0  InhibitRightGate
//
// Edges:
//   readGateToI0      readGate14.out -> i0Test3.in
//   i0ToI1            i0Test3.out -> myInhibitor.in
//   i1AckToReadGate   myInhibitor.out -> readGate14.ack
//   inputToReadGate   in0test.out -> readGate14.chainIn
//   i0ToInhibitRight  i0Test3.inhibitOut -> inhibitRight0.left
//   i1ToInhibitRight  myInhibitor.inhibitOut -> inhibitRight0.right

package Wiring

import (
	CI "github.com/dtauraso/wirefold/ChainInhibitorNode"
	IRG "github.com/dtauraso/wirefold/InhibitRightGateNode"
	INN "github.com/dtauraso/wirefold/InputNode"
	RGN "github.com/dtauraso/wirefold/ReadGateNode"
	S "github.com/dtauraso/wirefold/SafeWorker"
)

func Wire() []S.Node {
	// Channels
	readGateToI0 := make(chan int, 1)
	i0ToI1 := make(chan int, 1)
	i1AckToReadGate := make(chan int, 1)
	inputToReadGate := make(chan int, 1)
	i0ToInhibitRight := make(chan int, 1)
	i1ToInhibitRight := make(chan int, 1)

	// Edge priming
	i1AckToReadGate <- 1

	// Input externals
	in0testInput := make(chan int, 3)
	in0testInput <- 0
	in0testInput <- 1
	in0testInput <- 0

	// Dead-end outputs
	i0Test3Ack := make(chan int, 1)
	myInhibitorAck := make(chan int, 1)
	inhibitRight0Out := make(chan int, 1)

	// Nodes
	in0test := INN.InputNode{Id: 0, Name: "in0test", Input: in0testInput, ToNext: inputToReadGate}
	readGate14 := RGN.ReadGateNode{Id: 0, Name: "readGate14", FromAck: i1AckToReadGate, FromValue: inputToReadGate, ToLatch: readGateToI0}
	i0Test3 := CI.ChainInhibitorNode{Id: 0, Name: "i0Test3", FromPrev: readGateToI0, ToAck: i0Test3Ack, ToEdge: []chan<- int{i0ToInhibitRight}, ToNext: i0ToI1}
	myInhibitor := CI.ChainInhibitorNode{Id: 1, Name: "myInhibitor", FromPrev: i0ToI1, ToAck: myInhibitorAck, ToEdge: []chan<- int{i1ToInhibitRight}, ToNext: i1AckToReadGate}
	inhibitRight0 := IRG.InhibitRightGateNode{Id: 0, Name: "inhibitRight0", FromLeft: i0ToInhibitRight, FromRight: i1ToInhibitRight, ToOut: inhibitRight0Out}

	return []S.Node{&in0test, &readGate14, &i0Test3, &myInhibitor, &inhibitRight0}
}
