// GENERATED by tools/gen-node-defs — do not edit. Source: nodes/<Kind>/<Kind>.go wire:"data.*" tags.
// Validates node.data blobs against Go struct field types.

import { ParseError } from "./parse-primitives";

export interface ChainInhibitorData {
  initialSlots: {
    held: number;
  };
}

export interface InputData {
  init: number[];
}

// parseNodeData validates node.data for known kinds. Unknown kinds pass through.
// Throws ParseError if the data shape does not match the Go struct.
export function parseNodeData(kind: string, data: unknown, path: string): unknown {
  if (data === undefined || data === null) return data;
  switch (kind) {
    case "ChainInhibitor": {
      if (typeof data !== "object" || Array.isArray(data)) throw new ParseError(path+".data: expected object");
      const d = data as Record<string, unknown>;
    { const p = d["initialSlots"] as Record<string, unknown>|undefined; if (!p || typeof p !== "object") throw new ParseError(path+".data.initialSlots: expected object"); if (typeof p["held"] !== "number") throw new ParseError(path+".data.initialSlots.held: expected number"); }
      return data;
    }
    case "Input": {
      if (typeof data !== "object" || Array.isArray(data)) throw new ParseError(path+".data: expected object");
      const d = data as Record<string, unknown>;
    if (!Array.isArray(d["init"]) || !(d["init"] as unknown[]).every((x) => typeof x === "number")) throw new ParseError(path+".data.init: expected number[]");
      return data;
    }
    default:
      return data;
  }
}
