// Code generated by topogen — DO NOT EDIT.
//
// Spec summary: 5 nodes, 6 edges.
//
// Nodes:
//   in0test           Input
//   readGate14344444  ReadGate
//   i0Test423         ChainInhibitor
//   i1                ChainInhibitor
//   inhibitRight0     InhibitRightGate
//
// Edges:
//   readGateToI0      readGate14344444.out -> i0Test423.in
//   i0ToI1            i0Test423.out -> i1.in
//   i1AckToReadGate   i1.out -> readGate14344444.ack
//   inputToReadGate   in0test.out -> readGate14344444.chainIn
//   i0ToInhibitRight  i0Test423.inhibitOut -> inhibitRight0.left
//   i1ToInhibitRight  i1.inhibitOut -> inhibitRight0.right

package Wiring

import (
	CI "github.com/dtauraso/wirefold/nodes/ChainInhibitorNode"
	IRG "github.com/dtauraso/wirefold/nodes/InhibitRightGateNode"
	INN "github.com/dtauraso/wirefold/nodes/InputNode"
	RGN "github.com/dtauraso/wirefold/nodes/ReadGateNode"
	S "github.com/dtauraso/wirefold/nodes/SafeWorker"
)

func Wire() []S.Node {
	// Channels
	readGateToI0 := make(chan int, 1)
	i0ToI1 := make(chan int, 1)
	i1AckToReadGate := make(chan int, 1)
	inputToReadGate := make(chan int, 1)
	i0ToInhibitRight := make(chan int, 1)
	i1ToInhibitRight := make(chan int, 1)

	// Edge priming
	i1AckToReadGate <- 1

	// Input externals
	in0testInput := make(chan int, 3)
	in0testInput <- 0
	in0testInput <- 1
	in0testInput <- 0

	// Dead-end outputs
	i0Test423Ack := make(chan int, 1)
	i1Ack := make(chan int, 1)
	inhibitRight0Out := make(chan int, 1)

	// Nodes
	in0test := INN.InputNode{Id: 0, Name: "in0test", Input: in0testInput, ToNext: inputToReadGate}
	readGate14344444 := RGN.ReadGateNode{Id: 0, Name: "readGate14344444", FromAck: i1AckToReadGate, FromValue: inputToReadGate, ToLatch: readGateToI0}
	i0Test423 := CI.ChainInhibitorNode{Id: 0, Name: "i0Test423", FromPrev: readGateToI0, ToAck: i0Test423Ack, ToEdge: []chan<- int{i0ToInhibitRight}, ToNext: i0ToI1}
	i1 := CI.ChainInhibitorNode{Id: 1, Name: "i1", FromPrev: i0ToI1, ToAck: i1Ack, ToEdge: []chan<- int{i1ToInhibitRight}, ToNext: i1AckToReadGate}
	inhibitRight0 := IRG.InhibitRightGateNode{Id: 0, Name: "inhibitRight0", FromLeft: i0ToInhibitRight, FromRight: i1ToInhibitRight, ToOut: inhibitRight0Out}

	return []S.Node{&in0test, &readGate14344444, &i0Test423, &i1, &inhibitRight0}
}
