// Code generated by topogen — DO NOT EDIT.
//
// Spec summary: 6 nodes, 7 edges.
//
// Nodes:
//   in08           Input
//   readGate1      ReadGate
//   i0             ChainInhibitor
//   i1             ChainInhibitor
//   inhibitRight0  InhibitRightGate
//   bootstrap_rg   Input
//
// Edges:
//   inputToReadGate         in08.out -> readGate1.value
//   readGateToI0            readGate1.gated -> i0.in
//   i0ToI1                  i0.out -> i1.in
//   i0InhibitToRight0Left   i0.inhibitOut -> inhibitRight0.left
//   i1InhibitToRight0Right  i1.inhibitOut -> inhibitRight0.right
//   i1ToReadGate            i1.out -> readGate1.ack
//   bootstrapRgToReadGate   bootstrap_rg.out -> readGate1.ack

package Wiring

import (
	CI "github.com/dtauraso/wirefold/nodes/ChainInhibitorNode"
	IRG "github.com/dtauraso/wirefold/nodes/InhibitRightGateNode"
	INN "github.com/dtauraso/wirefold/nodes/InputNode"
	RGN "github.com/dtauraso/wirefold/nodes/ReadGateNode"
	S "github.com/dtauraso/wirefold/nodes/SafeWorker"
)

func Wire() []S.Node {
	// Channels
	inputToReadGate := make(chan int, 1)
	readGateToI0 := make(chan int, 1)
	i0ToI1 := make(chan int, 1)
	i0InhibitToRight0Left := make(chan int, 1)
	i1InhibitToRight0Right := make(chan int, 1)
	i1ToReadGate := make(chan int, 1)
	bootstrapRgToReadGate := make(chan int, 1)

	// Input externals
	in08Input := make(chan int, 2)
	in08Input <- 0
	in08Input <- 1
	bootstrap_rgInput := make(chan int, 1)
	bootstrap_rgInput <- 1

	// Dead-end outputs
	i0Ack := make(chan int, 1)
	i1Ack := make(chan int, 1)
	inhibitRight0Passed := make(chan int, 1)

	// Nodes
	in08 := INN.InputNode{Id: 0, Name: "in08", Input: in08Input, ToNext: inputToReadGate}
	readGate1 := RGN.ReadGateNode{Id: 0, Name: "readGate1", FromValue: inputToReadGate, FromAck: bootstrapRgToReadGate, ToGated: readGateToI0}
	i0 := CI.ChainInhibitorNode{Id: 0, Name: "i0", HeldValue: 0, FromPrev: readGateToI0, ToAck: i0Ack, ToEdge: []chan<- int{i0InhibitToRight0Left}, ToNext: i0ToI1}
	i1 := CI.ChainInhibitorNode{Id: 0, Name: "i1", HeldValue: 0, FromPrev: i0ToI1, ToAck: i1Ack, ToEdge: []chan<- int{i1InhibitToRight0Right}, ToNext: i1ToReadGate}
	inhibitRight0 := IRG.InhibitRightGateNode{Id: 0, Name: "inhibitRight0", FromLeft: i0InhibitToRight0Left, FromRight: i1InhibitToRight0Right, ToPassed: inhibitRight0Passed}
	bootstrap_rg := INN.InputNode{Id: 0, Name: "bootstrap_rg", Input: bootstrap_rgInput, ToNext: bootstrapRgToReadGate}

	return []S.Node{&in08, &readGate1, &i0, &i1, &inhibitRight0, &bootstrap_rg}
}
