// Code generated by topogen — DO NOT EDIT.
//
// Spec summary: 6 nodes, 7 edges.
//
// Nodes:
//   in08           Input
//   readGate1      ReadGate
//   i0             ChainInhibitor
//   i1             ChainInhibitor
//   inhibitRight0  InhibitRightGate
//   bootstrap_rg   Input
//
// Edges:
//   in08ToReadGate1         in08.ToOut -> readGate1.FromValue
//   readGate1ToI0           readGate1.ToGated -> i0.FromPrev
//   i0ToI1                  i0.ToNext -> i1.FromPrev
//   i0ToInhibitRight0       i0.ToEdge -> inhibitRight0.FromLeft
//   i1ToInhibitRight0       i1.ToEdge -> inhibitRight0.FromRight
//   i1ToReadGate1           i1.ToNext -> readGate1.FromAck
//   bootstrapRgToReadGate1  bootstrap_rg.ToOut -> readGate1.FromAck

package Wiring

import (
	CI "github.com/dtauraso/wirefold/nodes/ChainInhibitorNode"
	IRG "github.com/dtauraso/wirefold/nodes/InhibitRightGateNode"
	INN "github.com/dtauraso/wirefold/nodes/InputNode"
	RGN "github.com/dtauraso/wirefold/nodes/ReadGateNode"
	S "github.com/dtauraso/wirefold/nodes/SafeWorker"
)

func Wire() []S.Node {
	// Channels
	in08ToReadGate1 := make(chan int, 1)
	readGate1ToI0 := make(chan int, 1)
	i0ToI1 := make(chan int, 1)
	i0ToInhibitRight0 := make(chan int, 1)
	i1ToInhibitRight0 := make(chan int, 1)
	i1ToReadGate1 := make(chan int, 1)
	bootstrapRgToReadGate1 := make(chan int, 1)

	// Input externals
	in08Input := make(chan int, 2)
	in08Input <- 0
	in08Input <- 1
	bootstrap_rgInput := make(chan int, 1)
	bootstrap_rgInput <- 1

	// Dead-end outputs
	i0ToAck := make(chan int, 1)
	i1ToAck := make(chan int, 1)
	inhibitRight0ToPassed := make(chan int, 1)

	// Nodes
	in08 := INN.InputNode{Id: 0, Name: "in08", Input: in08Input, ToNext: in08ToReadGate1}
	readGate1 := RGN.ReadGateNode{Id: 0, Name: "readGate1", FromAck: bootstrapRgToReadGate1, FromValue: in08ToReadGate1, ToGated: readGate1ToI0}
	i0 := CI.ChainInhibitorNode{Id: 0, Name: "i0", HeldValue: 0, FromPrev: readGate1ToI0, ToAck: i0ToAck, ToEdge: []chan<- int{i0ToInhibitRight0}, ToNext: i0ToI1}
	i1 := CI.ChainInhibitorNode{Id: 0, Name: "i1", HeldValue: 0, FromPrev: i0ToI1, ToAck: i1ToAck, ToEdge: []chan<- int{i1ToInhibitRight0}, ToNext: i1ToReadGate1}
	inhibitRight0 := IRG.InhibitRightGateNode{Id: 0, Name: "inhibitRight0", FromLeft: i0ToInhibitRight0, FromRight: i1ToInhibitRight0, ToPassed: inhibitRight0ToPassed}
	bootstrap_rg := INN.InputNode{Id: 0, Name: "bootstrap_rg", Input: bootstrap_rgInput, ToNext: bootstrapRgToReadGate1}

	return []S.Node{&in08, &readGate1, &i0, &i1, &inhibitRight0, &bootstrap_rg}
}
