// gen-kind-imports walks nodes/*/ and writes kinds_generated.go at the
// repo root with blank imports for every package that calls Wiring.Register.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	// Determine repo root: generator is run from repo root via go generate.
	repoRoot, err := os.Getwd()
	if err != nil {
		fatalf("getwd: %v", err)
	}

	nodesDir := filepath.Join(repoRoot, "nodes")
	entries, err := os.ReadDir(nodesDir)
	if err != nil {
		fatalf("readdir nodes: %v", err)
	}

	modulePath := "github.com/dtauraso/wirefold"

	var kinds []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pkgDir := filepath.Join(nodesDir, e.Name())
		if hasRegister(pkgDir) {
			kinds = append(kinds, e.Name())
		}
	}
	sort.Strings(kinds)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/gen-kind-imports. DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\nimport (\n")
	for _, k := range kinds {
		fmt.Fprintf(&buf, "\t_ %q\n", modulePath+"/nodes/"+k)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatalf("format: %v", err)
	}

	out := filepath.Join(repoRoot, "kinds_generated.go")
	if err := os.WriteFile(out, formatted, 0644); err != nil {
		fatalf("write %s: %v", out, err)
	}
	fmt.Fprintf(os.Stderr, "gen-kind-imports: wrote %s (%d kinds)\n", out, len(kinds))
}

// hasRegister reports whether any .go file in dir contains "Wiring.Register(".
func hasRegister(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		if bytes.Contains(data, []byte("Wiring.Register(")) {
			return true
		}
	}
	return false
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-kind-imports: "+format+"\n", args...)
	os.Exit(1)
}
